[versions]
# Build Tools & Language
agp = "8.13.0"
kotlin = "2.2.0"
jetbrainsKotlinJvm = "2.3.0"

# AndroidX Core
coreKtx = "1.17.0"
appcompat = "1.7.1"
coreSplashscreen = "1.2.0"

# Compose & UI Libraries
material3 = "1.4.0"
composeBom = "2026.01.00"
activityCompose = "1.12.2"
navigationCompose = "2.9.6"
lifecycleRuntimeKtx = "2.10.0"
lifecycleViewmodelKtx = "2.10.0"
# foundation 및 layout 중복 버전 통합
foundation = "1.7.6"
foundationLayout = "1.7.6"
runtime = "1.7.6"
coil3 = "3.3.0"

# Google & Firebase
firebaseBom = "34.7.0"
googleGmsServices = "4.4.4"
playServicesAuth = "21.5.0"
material = "1.13.0" # XML Material Components

# Database & Storage
room = "2.7.2"
datastore = "1.0.0"
gson = "2.10.1"

# Others
kotlinxCoroutinesCore = "1.10.2"
kotlinxSerializationJson = "1.9.0"
ksp = "2.2.0-2.0.2"
mpAndroidChart = "v3.1.0"
volley = "1.2.1"

# Test Tools
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
firebaseMessagingKtx = "25.0.1"

[libraries]
# AndroidX & Appcompat
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "coreSplashscreen" }

# Compose Main
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "runtime" }

# Compose Foundation & Layout
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout", version.ref = "foundationLayout" }

# Navigation & Lifecycle
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }

# Firebase
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth" }
firebase-storage = { group = "com.google.firebase", name = "firebase-storage" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging" }
play-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "playServicesAuth" }

# Local DB & Others
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
#coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil3" }
coil-network-okhttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil3" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
mpAndroidChart = { group = "com.github.PhilJay", name = "MPAndroidChart", version.ref = "mpAndroidChart" }
volley = { group = "com.android.volley", name = "volley", version.ref = "volley" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }

# Test
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
firebase-messaging-ktx = { group = "com.google.firebase", name = "firebase-messaging-ktx", version.ref = "firebaseMessagingKtx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin"}
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsServices" }

[bundles]
compose-libraries = [
    "androidx-activity-compose",
    "androidx-compose-material3",
    "androidx-lifecycle-runtime-ktx",
    "androidx-compose-ui",
    "androidx-compose-ui-graphics",
    "androidx-compose-ui-tooling",
    "androidx-compose-ui-tooling-preview",
    "androidx-navigation-compose",
    "androidx-compose-foundation",
    "androidx-compose-foundation-layout"
]
firebase-libraries = [
    "firebase-firestore",
    "firebase-auth",
    "firebase-storage",
    "firebase-messaging"
]
room-libraries = [
    "androidx-room-ktx",
    "androidx-room-runtime"
]